### ISSUE TITLE
Not launching

### ISSUE THREAD

**Issue by marekmaskarinec** [ProkopRandacek/rendering#4]
The launch process gets stuck on `141.15 -- GL - SHADER - vertex shader compiled`.

**Comment by ProkopRandacek** [comment]
How long did you wait? Shader linking (the stage after vertex shader compiling) can take up to multiple seconds on my high end machine when linking for the first time. It is possible that on a slower PCs it can take a long time. Maybe check that your gpu drivers are up to date?

**Comment by marekmaskarinec** [comment]
I ran it for a bit longer, and it eventually ran. I seem to have a different problem now.
![Uploading Screenshot from 2021-03-12 10-32-32.png…]()

**Comment by ProkopRandacek** [comment]
It looks like a hardware limitation. I don't think that I can do anything with this. Maybe the scene serialization upgrade that I am writing rn will save some shader code but I don't think that it will fix this.

**Comment by ProkopRandacek** [comment]
I reduced the shader size by 40 % in the last commit. Try running it now.

**Comment by marekmaskarinec** [comment]
Some person told me to write, that I have lower version of glsl, than required. It would be very unexpected, if you said, you already commited change to lower glsl version.

**Comment by ProkopRandacek** [comment]
Downgraded back to 3.3 in 20e0767

**Comment by marekmaskarinec** [comment]
Still doing this:

![Uploading Screenshot from 2021-03-13 11-03-05.png…]()

**Comment by ProkopRandacek** [comment]
That looks like a driver issue. I don't think that I can fix it.
